
app:
  title: "House Finder Pro"
  layout: "wide"
  port: 8501

paths:
  dataset: "AmesHousing.csv"
  database: "houses.db"
  model: "house_price_model.pkl"
  uploads: "uploads"

coordinates:
  default_lat: 42.0347
  default_lon: -93.6200

theme:
  default: "Light"

language:
  default: "English"
  supported:
    - "English"
    - "O‘zbek"
    - "Русский"
    - "Español"
